* HTMX

** Hypermedia

- Hypermedia :: Hypermedia is an HTML document that simultaneously provides
  markup structure for the document, and hypermedia controls (hyperlinks, form
  actions) for the application data. Hypermedia content is self-contained: it
  contains data, presentation markup, and operational hypermedia controls.
  Hypermedia is used as the primary engine for the application state HATEOAS
  - Server-driven UI :: The server is the single source of truth for the current
    application state, and possible next interactions
  - Zero-knowledge browser :: The browser acts purely as a hypermedia rendering
    engine with zero-knowledge about the application
  - HTML as API :: HTML is the primary API between the server and the browser
- Hypermedia controls :: Hypermedia controls transform static documents into an
  interactive applications with cross-document navigation and data submission
  capabilities. HTMX extends HTML by turning any HTML element into a hypermedia
  control. Hypermedia controls allow the browser to automatically and
  incrementally discover the application without any prior knowledge about the
  application
  - Hyperlink :: A hyperlink (anchor) tag navigates to and reads another HTML
    document specified by a hyper reference
#+begin_src web
<a href="https://hypermedia.systems/">Hypermedia</a>
#+end_src
  - Form action :: The form tag submits collected information to a resource
    identified by URL on the server
#+begin_src web
<form action="/signup" method="POST">
  <input type="text" name="email"/>
  <input type="password" name="password"/>
  <button type="submit">Sign up</buttong>
</form>
#+end_src
- URL :: Uniform Resource Locator URL is a reference including the access
  protocol to a resource on a network
#+begin_src fish
scheme://user@host:port/path?query#fragment
#+end_src

** REST

- REST :: REpresentational State Transfer REST is a client-server architecture
  with stateless communication through the uniform interface that allows for
  caching
- Uniform interface :: The uniform interface provides rolling release for
  continuous updates, and avoids complexities of JSON API versioning
  - Resource identification :: Uniform identification of resources through URLs
    automatically discovered from hypermedia responses
  - Resource representation :: Automatic negotiation of resource representation
    through the =Accept= and =Content-Type= HTTP headers
  - Resource manipulation :: Uniform manipulation of resources through HTTP
    verbs and semantic response status codes
| Verb   | Operation      | Characteristic |
|--------+----------------+----------------|
| POST   | Create         | Non-idempotent |
| PUT    | Full update    | Idempotent     |
| PATCH  | Partial update | Idempotent     |
| GET    | Read           | Read-only      |
| DELETE | Delete         | Idempotent     |

| Status code                  | Meaning                                         |
|------------------------------+-------------------------------------------------|
| 200 OK                       | Query success (read only)                       |
| 201 Created                  | Create success (non-idempotent)                 |
| 202 Accepted                 | Async processing (implies async notification)   |
| 204 No Content               | Update and delete success (idempotent)          |
|------------------------------+-------------------------------------------------|
| 400 Bad Request              | Invalid request format                          |
| 401 Unauthorized             | Missing authentication                          |
| 403 Forbidden                | Insufficient permissions                        |
| 404 Not Found                | Non-existing resource                           |
| 409 Conflict                 | Already existing resource (state conflict)      |
| 413 Request Entity Too Large | Request body exceeds limits                     |
| 422 Unprocessable Entity     | Invalid request semantic (constraint violation) |
| 429 Too Many Requests        | Rate-limit rejected request                     |
|------------------------------+-------------------------------------------------|
| 500 Internal Server Error    | Unexpected error (default)                      |
| 502 Bad Gateway              | Unavailable downstream service                  |
| 503 Service Unavailable      | Unavailable current service                     |
  - Self-describing messages, stateless communication :: Self-describing request
    and response messages including request and response headers contain all
    necessary information to process the request server-side and navigate the
    application client-side. Once a hypermedia application is entered into, all
    functionality and resources are automatically discovered through
    self-describing messages. The server handles requests without the need to
    remember previous requests
  - HATEOAS :: Hypermedia As The Engine Of Application State HATEOAS encodes the
    state of a resource in the markup and the actions available on the resource
    through hypermedia controls directly within the hypermedia response. A
    browser has zero knowledge about the resource to render and the application
    beyond the entry point URL
  - Caching :: Responses should specify caching behavior through the
    =Cache-Control= HTTP header
- Hypermedia API ::
  - Tailored HTML API :: Hypermedia API is tailored to a single HDA
  - Rolling release :: Hypermedia API can evolve in backward incompatible ways
    without breaking clients
  - Cookie-based session :: Hypermedia API uses a cookie-based, browser-handled
    session to authenticate clients
- JSON API ::
  - Generic JSON API :: JSON API must be generic to support variety of clients
    e.g. web, mobile, third-party systems, and scripts
  - Requires versioning :: JSON API must be stable and backward-compatible
    within each major version in order to not break clients
  - Token-based session :: JSON API requires explicitly managed token-based
    authentication of clients

** Hypermedia-driven application

- Hypermedia-driven application HDA :: A hypermedia-driven application HDA
  adheres to the REST network architecture, the HTML markup, the HTTP protocol,
  the uniform interface between hypermedia presenters (browsers) and hypermedia
  creators (servers), and native browser capabilities. Only hypermedia creators
  interact with external API e.g. identity providers, authorization servers,
  while hypermedia presenters only interact with hypermedia creators
#+begin_src web
<!-- Replace #contact with HTML fragment from GET /contact response -->
<button hx-get="/contact" hx-target="#contact">Contact</button>
#+end_src
- Locality of Behavior LoB :: The Locality of Behavior LoB states that behavior
  of a unit of code should be obvious from looking only at that unit of code.
  The LoB design pattern is the opposite of the SoC design pattern
- Scripting in hypermedia-driven applications :: Data, presentation, and
  behavior of HDA are controlled by the hypermedia created, the server.
  Client-side interactivity is delegated to scripting
  - Hypermedia format :: Scripting must preserve the hypermedia format (HTML
    over HTTP) between the browser and the server
  - DOM-managed state :: Scripting should store state in the DOM (element
    attributes), so the state is automatically exchanged with the server without
    client-side data modeling
  - Listen to events :: Scripting should listen to standard and custom events,
    instead of registering callbacks on fragile selectors
#+begin_src web
<script>
 function sweetConfirm(el, config) {
   const res = await Swal.fire(config)
   if (res.isConfirmed) {
     el.dispatchEvent(new Event("confirmed"))
   }
 }
</script>

<button type="button"
  hx-delete="/contact"
  hx-target="body"
  hx-trigger="confirmed"
  @click='sweetConfirm($el, {title:"Delete contacts?"})'
>Delete contacts</button>
#+end_src
- JSON API :: JSON API provides only structured data without hypermedia
  controls, not a uniform interface. JSON API must be interpreted by a tailored
  custom SPA to render correctly
- Single Page Application SPA :: A Single Page Application SPA completely
  replaces the browser-native hypermedia system with structured JSON data
  exchange, complex client-side data modeling and state management,
  sophisticated two-way data binding between the in-memory client-side data
  model, the server state, and the DOM (tight coupling)

** =htmx= generalizations

- =htmx= generalizations ::
  - Any HTML element can issue HTTP requests and is a hypermedia control
    - =hx-boost= makes all children anchors and forms to issue async =fetch=,
      swap the =body= with the response without re-processing the =head=
      (scripts, style sheets), and updating the browser location bar
  - Any HTTP verb can be used in HTTP requests (=hx-get=, =hx-post=, =hx-put=,
    =hx-patch=, =hx-delete=)
  - Any event on any element can trigger HTTP requests (=hx-trigger=)
    - =hx-sync= synchronizes async requests from all children, so only one
      request at a time is issued, preventing concurrent async requests and
      uncontrolled swapping of DOM
  - HTML fragment from the response can replace the target DOM subtree within
    the current document without the full page reload (=hx-target=, =hx-swap=)
    - =hx-target= is automatically inherited by all child elements, so the
      children will target this outermost element
    - =tx-select= selects a subtree from a response to swap the target
- HTML form submission ::
  - Explicit form :: All form inputs are serialized into the request from any
    element within the form
#+begin_src web
<form>
  <label>
    <span>Search</span>
    <input type="search" name="query" value="{{request.body.query}}"/>
  </label>
  <button hx-post="/contact" hx-target="#contact">Search</button>
</form>
#+end_src
  - Explicit input include :: Explicitly select input elements (potentially
    outside of the form element) to be included in the request
#+begin_src web
<label>
  <span>Search</span>
  <input type="search" name="query" value="{{request.body.query}}" id="search"/>
</label>
<button hx-post="/contact" hx-target="#contact" hx-include="#search">Search</button>
#+end_src
- Error handling :: By default htmx does not swaps content on 4xx and 5xx status
  codes, unless explicitly configured otherwise

* Templ

** Component embedding

- Pure components :: Pure components depend only on passed arguments, without
  relaying on a global state, file system access, database queries, network
  calls
- Implicit context :: Templ components have an implicit =ctx= variable passed
  from the component =Render()= function. This context avoids property drilling,
  and provides access to values shared by the context in specific components
  down the line
#+begin_src web
package web

import "context"

func getUserID(ctx context.Context) string {
  userID, assert := ctx.Value("userID").(string)
  if !assert {
    return ""
  }
  return userID
}

templ SubComponent(content string) {
  <span>{content}</span>
  {children...}
}

templ Component(
  name, content string,
  attrs templ.Attributes,
  classes []string,
  subComponent templ.Component,
) {
  {{value := "scoped inline code"}}
  <div
    name={name}
    required?={true}
    {"data-" + name}={value}
    {attrs...}
    class={classes}
    class={templ.KV("primary", true)}
    if true {
      class={"active", name}
    }
  >
    Component {content} {getUserID(ctx)}
    @SubComponent("embedded") {
      <span>Children</span>
    }
    @subComponent
  </div>
}
#+end_src

#+begin_src go
// > templ generate
func main() {
  ctx := context.WithValue(context.Background(), "userID", "usr1234")
  name, content := "component", "content"
  attrs := map[string]any{
    "int": 1,
    "str": "two",
    "bool": true,
  }
  classes := []string{"a", "b", "c"}
  comp := web.Component(
    name, content, attrs, classes, web.SubComponent("embedded2"),
  )
  err := comp.Render(ctx, os.Stdout)
  if err != nil {
    fmt.Fprintf(os.Stderr, "%s\n", err)
    os.Exit(1)
  }
}
#+end_src

** Layout hierarchy

#+begin_src web
package web

// Component
templ Component(content string) {
  <div>{content}</div>
}

// Layout
templ Base(title string, component templ.Component) {
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>{title}</title>
  </head>
  <body>
      @component
      {children...}
  </body>
  </html>
}

// Page
templ Index() {
  @Base("Title", Component("Component")) {
    <div>Children</div>
  }
}
#+end_src
