* HTMX

** Hypermedia

- Hypermedia :: Hypermedia is an HTML document that simultaneously provides
  markup structure for the document, and hypermedia controls (hyperlinks, forms)
  for the application data. Hypermedia content is self-contained: it contains
  document content, structural markup, application data, and operational
  hypermedia controls (hyperlinks, forms). Hypermedia is used as the primary
  engine for the application state HATEOAS
  - Server-driven UI :: The server is the single source of truth for the current
    application state, and possible next interactions
  - Zero-knowledge browser :: The browser acts purely as a hypermedia rendering
    engine with zero-knowledge about the application
  - HTML as API :: HTML is the primary API between the server and the browser
- Hypermedia controls :: Hypermedia controls transform static documents into an
  interactive applications with cross-document navigation =<a>= and data
  submission capabilities =<form>=. HTMX extends HTML by turning any HTML
  element into a hypermedia control. Hypermedia controls allow the browser to
  automatically and incrementally discover the application without any prior
  knowledge about the application
  - Hyperlink :: A hyperlink (anchor) tag navigates =GET= to a location and
    reads content of another HTML document specified by a hyper reference
#+begin_src web
<!-- GET referenced document on click -->
<a href="https://hypermedia.systems/">Hypermedia</a>
#+end_src
  - Form action :: The form tag submits =POST/GET= collected data to a resource
    identified by a URL on the server
#+begin_src web
<!-- POST/GET collected data on submit -->
<form action="/signup" method="POST"></form>
#+end_src
- URL :: Uniform Resource Locator URL is a reference including the access
  protocol (scheme://) to a resource on a network e.g. HTML document, form
  submission endpoint
#+begin_src fish
scheme://user@host:port/path?query#fragment
#+end_src

** REST architecture

- REST :: REpresentational State Transfer REST is a client-server architecture
  between zero-knowledge browsers (hypermedia presenters) and single source of
  truth servers (hypermedia creators) with stateless communication through the
  uniform interface that allows for content caching
- Uniform interface :: The uniform interface provides rolling release for
  continuous application updates, and avoids complexities of JSON API versioning
  - Resource identification :: Uniform identification of resources through URLs
    automatically discovered from hypermedia responses
  - Resource representation :: Automatic negotiation of resource representation
    through the =Accept= request HTTP headers and =Content-Type= response HTTP
    headers
  - Resource manipulation :: Uniform manipulation of resources through HTTP
    verbs and semantic response status codes
| Verb   | Operation      | Characteristic |
|--------+----------------+----------------|
| POST   | Create         | Non-idempotent |
| PUT    | Full update    | Idempotent     |
| PATCH  | Partial update | Idempotent     |
| GET    | Read           | Read-only      |
| DELETE | Delete         | Idempotent     |

| Response status code         | Meaning                                         |
|------------------------------+-------------------------------------------------|
| 200 OK                       | Query success (read only)                       |
| 201 Created                  | Create success (non-idempotent)                 |
| 202 Accepted                 | Async processing (implies async notification)   |
| 204 No Content               | Update and delete success (idempotent)          |
|------------------------------+-------------------------------------------------|
| 400 Bad Request              | Invalid request format                          |
| 401 Unauthorized             | Missing authentication                          |
| 403 Forbidden                | Insufficient permissions                        |
| 404 Not Found                | Non-existing resource                           |
| 409 Conflict                 | Already existing resource (state conflict)      |
| 413 Request Entity Too Large | Request body exceeds limits                     |
| 422 Unprocessable Entity     | Invalid request semantic (constraint violation) |
| 429 Too Many Requests        | Rate-limit rejected request                     |
|------------------------------+-------------------------------------------------|
| 500 Internal Server Error    | Unexpected error (default)                      |
| 502 Bad Gateway              | Unavailable downstream service                  |
| 503 Service Unavailable      | Unavailable current service                     |
  - Self-describing messages, stateless communication :: Self-describing request
    and response messages including request and response HTTP headers contain
    all necessary information to process the request on the server and navigate
    the application in the browser. Once a hypermedia application is entered
    into, all functionality (forms) and resources (links) are automatically
    discovered through self-describing hypermedia requests and responses. The
    server handles requests without the need to remember previous requests
  - HATEOAS :: Hypermedia As The Engine Of Application State HATEOAS encodes the
    state of a resource in the markup, and the actions available on the resource
    through hypermedia controls directly within the hypermedia response. A
    browser has zero knowledge about the resource to render and the application
    to interact with beyond the entry point URL
  - Caching :: Responses should specify caching behavior through the
    =Cache-Control= HTTP header

*** Hypermedia API vs JSON API

- Hypermedia API ::
  - Tailored HTML API :: Hypermedia API is tailored to a single HDA
  - Rolling release :: Hypermedia API can evolve in backward incompatible ways
    without breaking clients
  - Cookie-based session :: Hypermedia API uses a cookie-based, browser-handled
    session to authenticate clients
- JSON API ::
  - Generic JSON API :: JSON API must be generic to support variety of clients
    e.g. web, mobile, third-party systems, and scripts
  - Requires versioning :: JSON API must be stable and backward-compatible
    within each major version in order to not break clients
  - Token-based session :: JSON API requires explicitly managed token-based
    authentication of clients

** Hypermedia-driven application

- Hypermedia-driven application HDA :: A hypermedia-driven application HDA
  adheres to the REST client-server architecture, the HTML markup, the HTTP
  protocol, the uniform interface between hypermedia presenters (browsers) and
  hypermedia creators (servers), and native browser capabilities. Only
  hypermedia creators internally interact with external API e.g. identity
  providers, authorization servers, while hypermedia presenters only interact
  with hypermedia creators over the uniform interface
- Locality of Behavior LoB :: The Locality of Behavior states that behavior of a
  unit of code should be obvious from looking only at that unit of code. The LoB
  design pattern is the opposite of the Separation of Concerns SoC design
  pattern
- Scripting in hypermedia-driven applications :: Data, structure, and behavior
  of HDA are controlled by the hypermedia creator (server). Interactivity in the
  hypermedia presenter (browser) is delegated to client-side scripting
  - Preserve hypermedia communication format :: Scripting must preserve the
    hypermedia communication format (HTML over HTTP) between the browser and the
    server
  - Leverage DOM-managed state :: Scripting should exclusively store state in
    the DOM (element attributes), so the state is automatically exchanged with
    the server without complex client-side data modeling and data binding
  - Listen to events :: Scripting should listen to standard and custom events to
    communicate between components, instead of registering callbacks on fragile
    CSS selectors
  - Events for inline scripting :: Events are the primary integration method
    between HTMX and alpine.js inline scripting. Both HTMX and alpine.js can
    trigger events and respond to events
#+begin_src web
<script>
 function sweetConfirm(el, config) {
   const res = await Swal.fire(config)
   if (res.isConfirmed) {
     el.dispatchEvent(new Event("confirmed"))
   }
 }
</script>

<button type="button"
  hx-delete="/contact"
  hx-target="body"
  hx-trigger="confirmed"
  @click='sweetConfirm($el, {title:"Delete contacts?"})'
>Delete contacts</button>
#+end_src

*** JSON API and SPA

- JSON API :: JSON API provides only structured data without hypermedia
  controls, not a uniform interface. JSON API must be interpreted by a tailored
  custom SPA to render correctly
- Single Page Application SPA :: A Single Page Application SPA completely
  replaces the browser-native hypermedia system with structured JSON data
  exchange, complex client-side data modeling and state management,
  sophisticated two-way data binding between the in-memory client-side data
  model, the server state, and the DOM (tight coupling)

** HTMX generalizations

- HTMX generalizations :: HTMX provides declarative access to modern browser
  features directly from the server-rendered HTML, rather than imperative
  access from the client-side JavaScript

*** All elements as hypermedia controls

- Any HTML element :: Any HTML element becomes a hypermedia control, and can
  issue async HTTP requests
- Any HTTP verb :: Any HTTP verb can be used in async HTTP requests
| HTTP verb  | Description                |
|------------+----------------------------|
| =hx-get=   | Idempotent, read-only      |
| =hx-post=  | Non-idempotent, create     |
| =hx-put=   | Idempotent, full update    |
| =hx-patch= | Idempotent, partial update |
| =hx-delte= | Idempotent, delete         |

*** Request triggering

- Any trigger event :: Any event on any element can trigger async HTTP requests
- =hx-trigger= specifies events and conditions that trigger async HTTP requests
| Trigger                         | Description                                   |
|---------------------------------+-----------------------------------------------|
| =click=, =keyup=, =mouseup=     | Standard events                               |
| =click[boolean JS]=             | Event filter. Scope: first event, then global |
| =input changed delay:1s=        | Standard event modifiers (see below)          |
| =load=, =revealed=, =intersect= | HTMX non-standard events                      |
| =every <time> [boolean JS]=     | Periodic polling with optional filter         |
| =load, click delay:1s=          | Multiple independent triggers                 |
| =custom=                        | Custom events                                 |

| Standard event modifier       | Description                                      |
|-------------------------------+--------------------------------------------------|
| =once=                        | Only on the first event                          |
| =changed=                     | Only if the value has changed                    |
| =delay:<time>=                | Next event before delay resets current delay     |
| =throttle:<time>=             | Next event before delay is ignored               |
| =from:<selector>=             | Triggers on events from another element (=body=) |
| =consume=                     | Not triggers any other htmx request on parents   |
| =queue:<first,last,all,none>= | Event queuing during in-flight requests          |

| HTML element                  | Default trigger event |
|-------------------------------+-----------------------|
| =input=, =textarea=, =select= | =change=              |
| =form=                        | =submit=              |
| Other elements                | =click=               |
- =hx-sync= synchronizes async HTTP requests between this element and another
  element, so only one request at a time is issued, preventing concurrent
  requests and uncontrolled swapping
| Sync strategy                   | Description                                         |
|---------------------------------+-----------------------------------------------------|
| =drop= inter-element (default)  | Drop this new request, while in-flight old request  |
|                                 | Lock the element until server responds e.g. pay     |
| =abort= inter-element           | Abort in-flight old request, start this new request |
|                                 | Prioritize the most recent user action e.g. search  |
| =replace= same element          | Abort in-flight old request, start this new request |
| =queue first,last,all=          | Queue this request, while in-flight old requests    |

*** Targeting and swapping

- Any replace target :: HTML fragment from the response can replace any target
  DOM subtree within the current document without page reload
- =hx-target= targets for swapping a different element than the element that
  issued the async HTTP request. The default target is the element that issued
  the request
- =tx-select= selects a subtree from the response to swap the target
- =hx-swap= specifies how a response fragment swaps the target. A swap is either
  a full replacement of the target or a morph of the response fragment with
  existing DOM elements of the target
| Swap method   | Description                                         |
|---------------+-----------------------------------------------------|
| =innterHTML=  | Replaces inner HTML of the target element (default) |
| =outerHTML=   | Repaces the target element with response fragment   |
| =innerMorth=  | Preserves target children as much as possible       |
| =outerMorth=  | Preserves target as much as possible                |
| =textContent= | Replaces only text content of the target element    |
- =hx-partial= defines target and swapping for responses that update multiple
  elements
#+begin_src web
<hx-partial hx-target="#success" hx-swap="outerHTML">...</hx-partial>
#+end_src
- =hx-status= defines target and swapping for error responses. Multiple
  attributes are evaluated in order of specificity
#+begin_src web
<form hx-target="#success"
  hx-status:422="target:#validation-error swap:outerHTML"
  hx-status:4xx="#error"
  hx-status:5xx="#error"
>
</form>
#+end_src

*** HTMX design features

- HTMX attribute inheritance :: Most HTMX attributes are inherited and apply to
  the root element and its children. HTMX attribute inheritance avoid code
  duplication by hoisting HTMX attributes to the common parent element
- =CamelCase=, =kebab-case= events :: HTMX fires events with both =CamelCase=,
  =kebab-case=, which facilitates interoperability with other libraries

*** HTMX form submission

- State-changing vs read-only operations ::
  - =<a>= defines a read-only navigation via =GET=
  - =<form>=, =<button>= define state-changing idempotent =PUT=, =PATCH=,
    =DELETE=, or non-idempotent =POST= operations
- Request values :: The =value= of the element that issued the request is
  automatically included in the request. Values of all form inputs are
  automatically included in the form submission request
- POST/Redirect/GET :: Edit form URL should be pushed to the browser history.
  Resource mutation URL should not be pushed to the browser history
  - POST a create, update form. Authorize and mutate the resource
    - Directly return the form fragment with validation errors
  - 2xx with =HX-Location= response header for client-side automatic navigation
    to the mutated resource without page reload
  - GET the resource. Authorize and render the read-only view of the mutated
    resource
- HTMX form validation :: HTMX won't issue an async HTTP request or a WebSocket
  send if the form has validation errors. Non-form inputs do not validate before
  making the request by default, but =hx-validate= enables validation on
  non-form inputs. HTMX fires validation events that can be used to implement
  custom validation
| Validation event           | Purpose                                       |
|----------------------------+-----------------------------------------------|
| =htmx:validation:validate= | Add custom validation before HTML5 validation |
| =htmx:validation:failed=   | Show errors on invalid input                  |
| =htmx:validation:halted=   | Show validation errors preventing the request |
- Explicit form :: All form inputs within the enclosing =form= element are
  serialized into the request
#+begin_src web
<form>
  <label>
    <span>Search</span>
    <input type="search" name="query" value="{{request.body.query}}"/>
  </label>
  <button hx-post="/contact" hx-target="#contact">Search</button>
</form>
#+end_src
- Explicit input include :: Explicitly selected input elements (potentially
  outside of the =form= element) are serialized into the request
  - =hx-include= includes values of additional elements identified with the CSS
    selector in the async HTTP request
  - =hx-params= filters element values to be included into an async HTTP request
| Params value         | Description  |
|----------------------+--------------|
| =param1, param2=     | Include list |
| =not param1, param2= | Exclude list |
#+begin_src web
<label>
  <span>Search</span>
  <input type="search" name="query" value="{{request.body.query}}" id="search"/>
</label>
<button hx-post="/contact" hx-target="#contact" hx-include="#search">Search</button>
#+end_src

*** HTMX browser and server URLs

- Multi-URL without page reload ::
- Browser URL :: A browser URL represents read-only GET views of the application
  state e.g. list, detail, detail edit. Search, filter, sort, continuous scroll
  do not change the browser URL. Form mutation POST, PUT, PATCH URLs must
  never be pushed to the browser history, in order to avoid unintended
  modifications due to the double submit
- Server URL ::
- HTMX browser history :: =hx-push-url= creates a new browser history entry.
  =hx-replace-url= replaces the current browser history entry. HTMX caches the
  =body= DOM snapshot to the =localStorage=. HTMX restores the DOM snapshot from
  the =localStorage= on navigation via back/forward buttons without making a new
  request to the server. =hx-push-url= URLs must always be able to return a full
  page. For pages or fragments containing sensitive information disable history
  caching through ~hx-history="false"~
- Fragment vs full page response :: Every browser URL must support both fragment
  and full page response on the server. Given the HTMX configuration
  ~htmx.config.historyRestoreAsHxRequest = false~, the server returns a fragment
  response when the =HX-Request: true= request header is present, or a full page
  response otherwise

* Templ

** Component embedding

- Pure components :: Pure components depend only on passed arguments, without
  relaying on a global state, file system access, database queries, network
  calls
- Implicit context :: Templ components have an implicit =ctx= variable passed
  from the component =Render()= function. This context avoids property drilling,
  and provides access to values shared by the context in specific components
  down the line
#+begin_src web
package web

import "context"

func getUserID(ctx context.Context) string {
  userID, assert := ctx.Value("userID").(string)
  if !assert {
    return ""
  }
  return userID
}

templ SubComponent(content string) {
  <span>{content}</span>
  {children...}
}

templ Component(
  name, content string,
  attrs templ.Attributes,
  classes []string,
  subComponent templ.Component,
) {
  {{value := "scoped inline code"}}
  <div
    name={name}
    required?={true}
    {"data-" + name}={value}
    {attrs...}
    class={classes}
    class={templ.KV("primary", true)}
    if true {
      class={"active", name}
    }
  >
    Component {content} {getUserID(ctx)}
    @SubComponent("embedded") {
      <span>Children</span>
    }
    @subComponent
  </div>
}
#+end_src

#+begin_src go
// > templ generate
func main() {
  ctx := context.WithValue(context.Background(), "userID", "usr1234")
  name, content := "component", "content"
  attrs := map[string]any{
    "int": 1,
    "str": "two",
    "bool": true,
  }
  classes := []string{"a", "b", "c"}
  comp := web.Component(
    name, content, attrs, classes, web.SubComponent("embedded2"),
  )
  err := comp.Render(ctx, os.Stdout)
  if err != nil {
    fmt.Fprintf(os.Stderr, "%s\n", err)
    os.Exit(1)
  }
}
#+end_src

** Layout hierarchy

#+begin_src web
package web

templ Component(content string) {
  <div>{content}</div>
}

templ Layout(title string, component templ.Component) {
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{title}</title>
  </head>
  <body hx-ext="response-targets">
    @component
    {children...}
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js" integrity="sha384-H5SrcfygHmAuTDZphMHqBJLc3FhssKjG7w/CeCpFReSfwBWDTKpkzPP8c+cLsK+V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/htmx-ext-response-targets@2.0.4" integrity="sha384-T41oglUPvXLGBVyRdZsVRxNWnOOqCynaPubjUVjxhsjFTKrFJGEMm3/0KGmNQ+Pg" crossorigin="anonymous"></script>
  </body>
</html>
}

templ Page() {
  @Layout("Title", Component("Component")) {
    <div>Children</div>
  }
}
#+end_src

* Playwright

** Playwright architecture

- Playwright instance :: A Playwright instance manages different browsers
  #+begin_src go
  pw, err := playwright.Run()
  #+end_src
- Browser process (efficiency) :: Launch a single browser process for all tests
  in a test suite
  #+begin_src go
  browser, err := pw.Chromium.Launch()
  #+end_src
- Context session (isolation) :: A browser context represents an isolated
  browser session (cookies, local and session storage, permissions)
  #+begin_src go
  cx, err := browser.NewContext()
  #+end_src
- Page (parallelism) :: Multiple browser tabs share the same browser session and
  can execute tests in parallel
  #+begin_src go
  page, err := cx.NewPage()
  #+end_src

** Locators

- Locator :: A locator is a set of reliable query instructions to find an
  element on a page in face of dynamic DOM updates. A locator is lazily
  evaluated using auto-waiting (for unique, stable, visible, enabled elements)
  for every action that is performed on the locator. Locators are composable and
  can be chained. Locators can match multiple elements, and fail when the action
  does not support multiple elements
- Role-based locators (recommended) :: Role-based locators use ARIA
  accessibility attributes to find elements on a page by their meaning (role and
  visible text), not code structure (CSS selectors)
  #+begin_src go
  page.GetByRole(role, name string)
  #+end_src
- Text-based locators :: Text-based locators find elements by a user-visible
  text on a page
  #+begin_src go
  page.GetByText(text string) // Non-interactive elements
  page.GetByLabel(label string) // Interctive form controls
  #+end_src
- CSS locators (fragile) :: CSS locators find elements by CSS selectors e.g.
  code structure, specific attributes
  #+begin_src go
  page.Locator(selector string)
  #+end_src
- Locator chaining :: Chain multiple locators for precise and robust location of
  elements on a page
  #+begin_src go
  page.Locator("li").Filter({
    Has: Locator, HasText: "text",
  }).GetByRole("link").Click()
  #+end_src
