* Valkey

- Valkey :: Valkey is a distributed (async replication), in-memory, flat TTL
  keyspace of prefixed keys mapped to typed values. Valkey is a remote data
  structure server that provides atomic operations on String, Hash, List, Set,
  SortedSet in-memory data structures. Valkey acts as a fast, ephemeral
  operational store e.g. cache, session store, event store, rate limiting,
  message blocker, streaming engine
#+begin_src fish
docker run --interactive --tty --network sem_default \
  --rm valkey/valkey-bundle:9-trixie valkey-cli -h valkey
#+end_src

** Data types

- String :: A String is a sequence of bytes that can store any type of data e.g.
  text, numeric, bitmap, binary. A String is implemented using a Simple Dynamic
  String SDS with a constant time length lookup, binary safety, and
  type-dependent dynamic encoding e.g integer, header-embedded small strings,
  header-separated large strings
  - String operations ::
    - =set, get= O(1)
    - =mset, mget= O(1) multiple keys
    - =setrange, getrange= O(n)
    - =incr, decr= O(1) integer value
    - =incrby, decrby= O(1)
    - =append= O(1)
    - =strlen= O(1)
    - =getdel, getset= O(1)
    - =delifeq= O(1)
    - =setbit, getbit= O(1) memory-efficient array of bits
    - =bitop= O(n) and, or, xor, not
    - =bitcount= O(n) 0/1 total count
    - =bitpos= O(n) first 0/1 position
    - =bitfield= O(1) packed counters of arbitrary size signed/unsigned integers
  - String use cases ::
    - Cache text or binary data
    - Store blobs and serialized objects
    - Track real-time counters and metrics
    - Store session tokens and user information
    - Track bitmaps of user presence, preferences, or feature flags
    - Atomic acquire/release locks
- List :: A List is a doubly linked list (quicklist) of small arrays (listpacks)
  of ordered String values with constant time operations on the edges. A List
  supports blocking commands to implement a queue with producers and consumers.
  A String is consumed by exactly one consumer. After consumption a String is
  removed from the List
  - List operations ::
    - =lpush, rpush= O(1)
    - =lpop, rpop= O(1)
    - =blpop, brpop= O(1) blocking pop
    - =lmove, blmove= O(1) between two lists
    - =llen= O(1)
    - =lrange= O(n)
    - =lset= O(n) set by index
    - =lindex= O(n) get by index
    - =lpos= O(n) index of the first value
    - =linsert= O(n) before or after the first value
    - =lrem= O(n) remove by value
    - =ltrim= O(n)
  - List use cases ::
    - Schedule jobs for in-order processing
    - Store the last N items (via =ltrim=)
    - Implement a blocking queue
    - Implement a blocking stack
- Set :: A Set is an unordered collection of unique Strings with efficient
  membership check and efficient union, intersection, and difference operations.
  A Set is a hash table
  - Set operations ::
    - =sadd= O(1)
    - =sismember= O(1)
    - =srem= O(1)
    - =smove= O(1)
    - =scard= O(1)
    - =srandmember, spop= O(1) get, remove random element
    - =smembers= O(n) blocking, return all members at onece
    - =sscan= O(n) non-blocking, cursor-based, incremental iteration
    - =sunion, sunionstore= O(n)
    - =sinter, sinterstore= O(n)
    - =sdiff, sdiffstore= O(n)
  - Set use cases ::
    - Store unique values without duplicates e.g. tags, categories, permissions
    - Check membership and find out mutual friends
    - Perform set operations e.g. union, intersection, difference
- SortedSet :: A SortedSet is an ordered by a double precision score collection
  of unique Strings with efficient rank and range operations. Different Strings
  with the same score are ordered lexicographically by their representation
  bytes. A SortedSet consists of a hash table mapping a value to a score, and a
  skip list for efficient insertion, deletion, range, and rank operations
  ordered by score (similar to a balanced tree)
  - Skip list :: A skip list is a probabilistic ordered data structure that
    consists of multiple layered linked lists with logarithmic insert, delete,
    and search operations. A skip list provides an efficient range traversal
    with good CPU cache locality. A skip list requires minimal contained locks
    for concurrent access. The skip list delete operation has always predictable
    time without rebalancing rotations. A skip list is probabilistic, while
    balanced trees are deterministic. A skip list has a simpler implementation
    compared to balanced trees. A skip list consumes more memory than balanced
    trees
  - SortedSet operations ::
    - =zadd= O(log(n)) add member or update score of member
    - =zrem= O(log(n))
    - =zremrangebyscore, zremrangebyrank= O(log(n))
    - =zscore= O(1) return score of member
    - =zrandmember= O(1)
    - =zcard= O(1)
    - =zcount= O(log(n)) count members within range by score
    - =zrank, zrevrank= O(log(n)) return in-order position or index
    - =zrange, zrevrange= O(log(n)) range by rank, by score, by lex
    - =zpopmin, zpopmax= O(log(n))
    - =bzpopmin, bzpopmax= O(log(n)) blocking
    - =zincrby= O(log(n)) increment score of member
    - =zscan= O(n) non-blocking, cursor-based, incremental iteration
    - =zunion, zunionstore= O(n)
    - =zinter, zinterstore= O(n)
    - =zdiff, zdiffstore= O(n)
  - SortedSet use cases ::
    - Store leaderboards and rankings
    - Query top N elements
    - Schedule jobs priority-based processing
    - Implement sliding window rate limiter
    - Order time series by a timestamp score
    - Implement a priority queue
- Hash :: A Hash is a structure with field-value pairs.
- Stream :: A Stream is an append-only log of Hashes under monotonically
  increasing server-generated IDs =millisTime-sequenceNumber= with efficient
  random access, efficient range queries by ID, and fan out consumption via
  consumer groups. Clients in a consumer group must acknowledge processing of
  each delivered Hash. Multiple consumer groups can read a Stream. A Stream
  supports blocking commands to implement a stream with publishers and
  subscribers. Each Hash will be delivered to all subscribers by default. After
  delivery a Hash remains indefinitely in the Stream, unless explicitly removed
- Pub/Sub :: A Pub/Sub provides the at-most-once delivery of published messages
  to subscribes. A Pub/Sub is totally independent from the keyspace. A published
  message is delivered to all subscribers. A published message is lost if there
  are no subscribers
- Transactions =multi ... exec/discard= :: Transactions provide atomic execution
  of a group of queued commands without a rollback on failure. Command queuing
  errors discard the transaction. After queuing all commands are executed even
  if some commands fail
- Optimistic locking =watch/unwatch ... exec/discard= :: Optimistic locking
  provides the check-and-set monitoring of keys before =exec=. If at least one
  key is modified the transaction is aborted
- Secondary indices ::
  - Numeric field range query index :: Use a SortedSet =zadd/zrange= to build
    and range query an index on a numeric field mapping to a Hash ID
  - Lexicographical index :: Use a SortedSet =zadd/zrange= with the same 0 score
    for all elements. Every element can have appended extra fields (possibly
    padded) separated by =:= e.g. a frequency suffix that influences the rank of
    the element (composite index). The elements are sorted by their byte
    representation
- Distributed lock ::
  - Acquire a lock =set lock:resource lock_id nx ex 30=
  - Release a lock =delifeq lock:resource lock_id=
  - Otherwise a lock will be expired
- Valkey design patterns
  - Prefer efficient single key design to minimize the number of keys involved
    in a request
  - Design for expiration and explicit deletion of every key. Use TTL
    aggressively for ephemeral state to automatically remove expired data
  - Choose the data type by access pattern, not by data shape. Strings for
    values and counters. Hashes for structures of related data. Lists for
    efficient edge push and pop. Sets for efficient membership check of unique
    values. SortedSets for efficient ranking and range queries
  - Prefer non-blocking incremental scans over blocking full dumps of large
    collections
  - Use server-side Lua scripts for multi-step atomic logic e.g. check-then-act,
    read-modify-write, instead of =watch ... exec= optimistic locking with
    client-side checks and retries

** TODO

*** Development

- Key by entry vs Hash under a single key
- Bit fields
- Bit maps
- Bloom filters probabilistic
- HyperLogLog probabilistic
- DONE. Data types
- DONE. Distributed locks
- DONE. Hashes
- DONE. Key eviction
- DONE. Keyspace
- DONE. Lists
- DONE. Patterns example
- DONE. Pipelining
- DONE. Pub/Sub
- DONE. Sets
- DONE. Sorted sets
- DONE. Secondary indices
- DONE. Streams
- DONE. Strings
- DONE. Transactions
- Valkey JSON module
- Valkey search module

*** Deployment

- Configuration
- Persistence
- Replication
- Security
- ACL
