* Valkey

- Valkey :: Valkey is a distributed (async replication), in-memory, flat TTL
  keyspace of prefixed keys mapped to typed values. Valkey is a remote data
  structure server that provides atomic operations on String, Hash, List, Set,
  SortedSet in-memory data structures. Valkey acts as a fast, ephemeral
  operational store e.g. cache, session store, event store, rate limiting,
  message blocker, streaming engine
#+begin_src fish
docker run --interactive --tty --network sem_default \
  --rm valkey/valkey-bundle:9-trixie valkey-cli -h valkey
#+end_src

** Data structures

- String :: A String is a sequence of bytes that can store any type of data e.g.
  text, numeric, bitmap, binary. A String is implemented using a Simple Dynamic
  String SDS with a constant time length lookup, binary safety, and
  type-dependent dynamic encoding e.g integer, header-embedded small strings,
  header-separated large strings
  - String operations ::
    - =set, get= O(1)
    - =mset, mget= O(1) multiple keys
    - =setrange, getrange= O(n)
    - =incr, decr= O(1) integer value
    - =incrby, decrby= O(1)
    - =append= O(1)
    - =strlen= O(1)
    - =getdel, getset= O(1)
    - =delifeq= O(1)
    - =setbit, getbit= O(1) memory-efficient array of bits
    - =bitop= O(n) and, or, xor, not
    - =bitcount= O(n) 0/1 total count
    - =bitpos= O(n) first 0/1 position
    - =bitfield= O(1) packed counters of arbitrary size signed/unsigned integers
  - String use cases ::
    - Cache text or binary data
    - Store blobs and serialized objects
    - Track real-time counters and metrics
    - Store session tokens and user information
    - Track bitmaps of user presence, preferences, or feature flags
    - Atomic acquire/release locks
- Hash :: A Hash is a structure of String field-value pairs with efficient field
  level query and update under a single key. A Hash is a hash table
  - Hash operations ::
    - =hset, hget= O(1)
    - =hmset, hmget= O(1) set, get multiple fields
    - =hincrby= O(1)
    - =hexists= O(1)
    - =hdel= O(1)
    - =hlen= O(1)
    - =hkeys, hvals, hgetall= O(n)
    - =hscan= O(n)
  - Hash use cases ::
    - Store structures and objects e.g. user profile, user session
    - Cache structures and objects
- List :: A List is a doubly linked list (quicklist) of small arrays (listpacks)
  of ordered String values with constant time operations on the edges. A List
  supports blocking operations to implement a queue with producers and consumers.
  A String is consumed by exactly one consumer. After consumption a String is
  removed from the List
  - List operations ::
    - =lpush, rpush= O(1)
    - =lpop, rpop= O(1)
    - =blpop, brpop= O(1) blocking pop
    - =lmove, blmove= O(1) between two lists
    - =llen= O(1)
    - =lrange= O(n)
    - =lset= O(n) set by index
    - =lindex= O(n) get by index
    - =lpos= O(n) index of the first value
    - =linsert= O(n) before or after the first value
    - =lrem= O(n) remove by value
    - =ltrim= O(n)
  - List use cases ::
    - Schedule jobs for in-order processing
    - Store the last N items (via =ltrim=)
    - Implement a blocking queue
    - Implement a blocking stack
- Set :: A Set is an unordered collection of unique Strings with efficient
  membership check and efficient union, intersection, and difference operations.
  A Set is a hash table
  - Set operations ::
    - =sadd= O(1)
    - =sismember= O(1)
    - =srem= O(1)
    - =smove= O(1)
    - =scard= O(1)
    - =srandmember, spop= O(1) get, remove random element
    - =smembers= O(n) blocking, return all members at onece
    - =sscan= O(n) non-blocking, cursor-based, incremental iteration
    - =sunion, sunionstore= O(n)
    - =sinter, sinterstore= O(n)
    - =sdiff, sdiffstore= O(n)
  - Set use cases ::
    - Store unique values without duplicates e.g. tags, categories, permissions
    - Check membership and find out mutual friends
    - Perform set operations e.g. union, intersection, difference
- SortedSet :: A SortedSet is an ordered by a double precision score collection
  of unique Strings with efficient rank and range operations. Different Strings
  with the same score are ordered lexicographically by their representation
  bytes. A SortedSet consists of a hash table mapping a value to a score, and a
  skip list for efficient insertion, deletion, range, and rank operations
  ordered by score (similar to a balanced tree)
  - Skip list :: A skip list is a probabilistic ordered data structure that
    consists of multiple layered linked lists with logarithmic insert, delete,
    and search operations. A skip list provides an efficient range traversal
    with good CPU cache locality. A skip list requires minimal contained locks
    for concurrent access. The skip list delete operation has always predictable
    time without rebalancing rotations. A skip list is probabilistic, while
    balanced trees are deterministic. A skip list has a simpler implementation
    compared to balanced trees. A skip list consumes more memory than balanced
    trees
  - SortedSet operations ::
    - =zadd= O(log(n)) add member or update score of member
    - =zrem= O(log(n))
    - =zremrangebyscore, zremrangebyrank= O(log(n))
    - =zscore= O(1) return score of member
    - =zrandmember= O(1)
    - =zcard= O(1)
    - =zcount= O(log(n)) count members within range by score
    - =zrank, zrevrank= O(log(n)) return in-order position or index
    - =zrange, zrevrange= O(log(n)) range by rank, by score, by lex
    - =zpopmin, zpopmax= O(log(n))
    - =bzpopmin, bzpopmax= O(log(n)) blocking
    - =zincrby= O(log(n)) increment score of member
    - =zscan= O(n) non-blocking, cursor-based, incremental iteration
    - =zunion, zunionstore= O(n)
    - =zinter, zinterstore= O(n)
    - =zdiff, zdiffstore= O(n)
  - SortedSet use cases ::
    - Store leaderboards and rankings
    - Query top N elements
    - Schedule jobs priority-based processing
    - Implement sliding window rate limiter
    - Order time series by a timestamp score
    - Implement a priority queue
- Secondary index ::
  - SortedSet by score index :: The index =zadd= provides efficient
    =zrange/byscore= range queries by numeric values e.g. integers, timestamps.
    A secondary index is composed of a =SortedSet(score, Hash key)= efficient
    mapping, and a =key => Hash= structured storage. The index lookup combines
    two operations =zrange/byscore => Hash key=, =hgetall => Hash values=
  - SortedSet lexicographical index :: The index =zadd= provides efficient range
    =zrange/bylex= queries by representation bytes of Strings with the same 0
    score. Strings can have padded prefixes or suffixes that change the ordering

** Stream

- Stream :: A Stream is an append-only, persistent, time-ordered log of
  Hash-like field-value messages under monotonically increasing server-generated
  IDs =ms-seq=. A Stream provides a time-ordered sequence of messages, fan-out
  broadcast of every message to all consumers, workload distribution of messages
  between consumers in a consumer group, at-least-once delivery of messages in a
  consumer group. Each delivered message must be acknowledged by a consumer in a
  consumer group. Unacknowledged messages will be re-delivered to another
  consumer in a consumer group. After delivery a message remains indefinitely in
  the Stream, unless explicitly removed. A Stream supports blocking operations
  to implement a stream with producers and consumers. A stream is a radix tree
  of listpacks with efficient lookup by message ID and efficient range queries
  by ID prefix
  - Stream operations ::
    - =xadd= O(1)
    - =xlen= O(1)
    - =xread= O(log(n)) no consumer group, no automatic state tracking, no
      message ownership, no ack required, supports blocking
    - =xrange, xrevrange= O(n)
    - =xack= O(1)
    - =xdel= O(1)
    - =xtrim= O(1)
    - =xgroup= O(1)
    - =xreadgroup= O(1) read new messages and assign ownership within a consumer
      group, automatic server-side state tracking, requires ack
    - =xautoclaim= O(1) change ownership of unacknowledged messages in a
      consumer group
  - Stream use cases ::
    - Message broker with acknowledge-based, reliable delivery of messages
    - Job queue with workload distribution between consumers in a consumer group
    - Event sourcing of time-ordered message log e.g. audit log
    - Replay messages on recovery. Re-read the whole message history

** Transactions

- Transactions =multi cmds... exec/discard= :: Transactions provide atomic
  execution without interruption of a group of queued commands without a
  rollback on failure. Errors during command queuing discard the transaction.
  If a command fails during execution other commands are still executed
- Optimistic locking =watch/unwatch keys... multy cmds... exec/discard= ::
  Optimistic locking provides the check-and-set monitoring of keys before
  =exec=. If at least one key is modified between =watch= and =exec= the
  transaction is aborted, and the client must retry

** Locks

- Distributed lock :: A distributed lock on a single Valkey instance is a mutual
  exclusion with a lease window that coordinates access of multiple concurrent
  processes to a shared resource
  - Acquire a lock =set lock:resource lock_id nx ex 3=. Set expiration to
    prevent deadlocks. On failure, the current process waits, as the lock is
    already acquired by another process
  - Release a lock (only owner) =delifeq lock:resource lock_id=. The lock ID
    condition prevents incorrect release of a new lock by a delayed old owner,
    whose lease has already expired
  - Otherwise a lock will be expired

** Persistence

- RDB :: RDB is a point-in-time compact binary snapshot of the entire database
  stored on disk by a forked child process, with minimal impact on the serving
  parent process. The snapshot is either blocking =save= or non-blocking
  =bgsave=. RDB provides low runtime fork overhead, and fast restarts at the
  cost of bigger data loss (seconds to minutes). RDB is used as a periodic full
  backup
- AOF :: AOF is an append-only log of every write command that is replayed on
  restart. Every command is logged =appendfsync always=, or all commands since 1
  second are logged =appendfync everysec=. Background log compaction produces a
  minimal equivalent state. AOF provides minimal data loss (1 second) or no data
  loss at all at the cost of continuous runtime IO overhead, and slower restarts
  due to command replay. AOF is used to guarantee data durability
- ElastiCache multi-AZ :: The ElastiCache multi-AZ setup provides async data
  replication with automatic failover that promotes the stand by instance and
  replaces the crashed instance with a new stand by instance rebuilt from the
  current RDS snapshot and the recently buffered latest changes. ElastiCache
  Valkey does not support AOF

** Security

- ACL ::

** Valkey design patterns

- Prefer efficient single key design to minimize the number of keys involved in
  a request
- Design for expiration and explicit deletion of every key. Use TTL aggressively
  for ephemeral state to automatically remove expired data
- Choose the data type by access pattern, not by data shape. Strings for values
  and counters. Hashes for structures of related data. Lists for efficient edge
  push and pop. Sets for efficient membership check of unique values. SortedSets
  for efficient ranking and range queries
- Prefer non-blocking incremental scans over blocking full dumps of large
  collections
- Use server-side Lua scripts for multi-step atomic logic e.g. check-then-act,
  read-modify-write, instead of =watch ... exec= optimistic locking with
  client-side checks and retries

