* AWS network

** VPC

- VPC :: A Virtual Private Cloud is a logically isolated virtual network
  offering complete control over IP addressing, network segmentation, private,
  public, and isolated subnets, subnet availability, routing, security, and
  Internet access. An AWS account has a default VPC in each region. A VPC spans
  all AZs in a region
  | VPC netmask | Number of IPs |
  |-------------+---------------|
  | 10.0.0.0/16 |         65536 |
  | 10.0.0.0/20 |          4096 |
  | 10.0.0.0/24 |           256 |
  | 10.0.0.0/28 |            16 |
- VPC network segmentation ::
  - VPC 10.0.0.0/16
    - Public subnet 10.0.0.0/24 - Internet gateway inbound/outbound Internet
      - API gateway, ALB, NAT gateway
    - Private subnet 10.0.1.0/24 - NAT gateway outbound-only Internet
      - API containers, ECS tasks (services, jobs), SQS consumers
    - Isolated subnet 10.0.1.0/24 - No Internet access
      - RDS database service, Aurora database cluster
- CIDR addressing :: Classless Inter-Domain Routing ~network IP/network mask~
  allows for flexible division of IP ranges between subnets e.g. 10.0.0.0/16.
  Break the main VPC CIDR/16 into smaller non-overlapping CIDR/20 blocks per
  environment and further into CIDR/24 blocks for public and private subnets
- Separate VPC per environment :: Separate VPC per environment provides far
  stronger isolation, security, and independent operation
  | Env   | VPC          | Pub subnet ALB | Prv subnet ECS | Iso subnet RDS |
  |-------+--------------+----------------+----------------+----------------+
  | dev   | 10.10.0.0/20 | 10.10.0.0/24   | 10.10.16.0/24  | 10.10.32.0/24  |
  | stage | 10.20.0.0/20 | 10.20.0.0/24   | 10.20.16.0/24  | 10.20.32.0/24  |
  | prod  | 10.30.0.0/16 | 10.30.0.0/20   | 10.30.48.0/20  | 10.30.96.0/20  |
- Environments and subnets :: The main VPC 10.0.0.0/16 has up to 16 /20 CIDR
  blocks for different environments. Each /20 CIDR block has up to 16 /24
  public, private and isolated subnets. Each subnet has up to 256 - 5 reserved =
  251 IP addresses for servers
  | Env   | VPC CIDR     | Public subnet | Private subnet | Isolated subnet |
  |-------+--------------+---------------+----------------+-----------------|
  | dev   | 10.0.0.0/20  | 10.0.0.0/24   | 10.0.1.0/24    | 10.0.2.0/24     |
  | stage | 10.0.16.0/20 | 10.0.16.0/24  | 10.0.17.0/24   | 10.0.18.0/24    |
  | prod  | 10.0.32.0/20 | 10.0.32.0/24  | 10.0.33.0/24   | 10.0.34.0/24    |
- Subnet :: A subnet is a logical subdivision of VPC IP range within a single AZ
  between public, private, and isolated subnets. VPC reserves 5 IP addresses per
  subnet for internal use. Separate RDS databases with no Internet access
  (isolated subnet), from ECS tasks (services, jobs) and SQS consumers with
  outbound-only Internet access (private subnet) to define the network
  segmentation, enforce the least privilege, and the defense in depth principles
  using fine grained routing table rules, stricter security groups, and network
  ACL. Deploy components to multiple (at least 2) AZ for high availability e.g.
  API containers, SQS consumers. Tag all subnets with =environment.AZ.component=
- Route table :: A route table directs traffic to an Internet gateway, a NAT
  gateway, or to other subnets. Keep inter-service communication within VPC, not
  over Internet
- Internet gateway :: An Internet gateway enables bidirectional access to
  Internet for public subnets
- NAT gateway :: A NAT gateway enables instances in a private subnet to access
  Internet without being exposed to inbound traffic. AWS automatically load
  balances traffic between NAT gateways in different subnets/AZs
- Network ACL :: A network ACL is a stateless, subnet-level firewall at the
  subnet level for coarse-grained network security. Network ACL have both allow
  and deny rules. Rules evaluation order matters

** Route table

- Route table :: A route table decides the next network hop by specifying a
  destination network prefix and a routing target e.g. Internet gateway, NAT
  gateway, Transit gateway, VPC peering. VPC owns all route tables including the
  default main route table. Each subnet is associated with exactly one route
  table either explicitly or implicitly with the main route table. Multiple
  subnets can share the same route table. Route table rules
  #+begin_src yaml
  # Local VPC (always present)
  Destination: 10.0.0.0/16 # VPC CIDR
  Target: local
  # Bidirectional Internet (public subnet)
  Destination: 0.0.0.0/0
  Target: Internet gateway ID
  # Outbound Internet (private subnet)
  Destination: 0.0.0.0/0
  Target: NAT gateway ID
  # Other VPCs
  Destination: 10.1.0.0/16 # Other VPC CIDR
  Target: VPC peering, Transit gateway ID
  # On premise network
  Destination: Network IP
  Target: Direct connect, VPN
  #+end_src

** Internet gateway

- Internet gateway :: The Internet gateway is a fully managed, highly available,
  horizontally scalable VPC component that enables the inbound and outbound
  Internet access for instances with public IPs or Elastic IPs in public
  subnets. The Internet gateway is attached to a VPC, not public subnets. Only
  one Internet gateway can be attached to a VPC. Multiple public subnets can be
  attached to a single Internet gateway. A public subnet must have a route
  targeting an Internet gateway. The Internet gateway supports both IPv4 and
  IPv6.

** NAT gateway

- NAT gateway :: The NAT gateway is a fully managed, highly available,
  horizontally scalable VPC component that enables only the outbound Internet
  access for instances with private IPs in private subnets. The NAT gateway
  enables AWS resources in private subnets access the Internet without being
  exposed to the Internet. A NAT gateway must be placed in a public subnet. An
  Elastic IP must be attached to a NAT gateway. Use one NAT gateway per
  availability zone. A private subnet must have a route targeting a NAT gateway.
  The flow is: ~private EC2 => NAT gateway => Internet gateway => Internet~. The
  NAT gateway support only IPv4 (use the Egress-only Internet gateway for IPv6).

** Transit gateway

- Transit gateway :: The Transit gateway is a fully manage, highly available,
  horizontally scalable AWS networking service that acts as a central hub for
  connecting multiple networks e.g. VPCs via VPC attachments, other AWS regions
  via Transit gateway peering, on-premises networks via VPN connections, private
  data centers via Direct connect. The Transit gateway provides centralized
  routing between multiple networks, route segmentation through multiple route
  tables, and traffic control through routing policies. The Transit gateway
  supports transitive routing ~A => B => C~
- The Transit gateway use cases
  - Large multi-VPC network architectures
  - Large multi-region network architectures
  - Large hybrid cloud network architectures

** VPC peering

- VPC peering :: The VPC peering provides a direct point-to-point private,
  potentially cross-account and cross-region connection between two VPCs. The
  VPC peering allows two VPCs with non-overlapping CIDR blocks to communicate
  directly using private IPs as if they were part of the same network. VPC
  peering does not support transitive connectivity, ~A => B~ only. Route tables
  of each VPC must be updated to enable VPC peering
  #+begin_src yaml
  # VPC-A 10.0.0.0/16
  Destination: 10.1.0.0/16 # VPC-B
  Target: VPC peering ID
  # VPC-B 10.1.0.0/16
  Destination: 10.0.0.0/16 # VPC-A
  Target: VPC peering ID
  #+end_src

** Direct connect

- Direct connect :: The Direct connect is a service that provides dedicated,
  private (not over the Internet), low-latency, high-bandwidth network
  connections between an on-premises data center and VPCs, AWS resources. The
  Direct connect can use a VPN connection over Internet as a failover

** PrivateLink

- PrivateLink :: The PrivateLink is a network service that enables private
  connections inside the AWS network to AWS resources, private services in
  another VPC without exposing traffic to the Internet (without the Internet
  gateway, the NAT gateway, the Transit gateway, the VPC peering)

** Security groups

- Security group :: A SG is a fine-grained, stateful, virtual firewall that
  controls inbound and outbound traffic at the instance level and a port or the
  ENI level. SGs are stateful, so if inbound traffic on a port is allowed, than
  the outbound traffic is automatically allowed, and vice versa. SGs have only
  allow rules, not deny rules. Use SG referencing to allow access from one SG to
  another, instead of IPs or networks e.g. 0.0.0.0/0. SGs scale automatically
  with EC2 instances or ECS services they protect. By default all egress
  0.0.0.0/0 is allowed unless overridden
